# Generated by Django 6.0 on 2025-12-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='Manually added item (not from recipe)'),
        ),
    ]
