# Generated by Django 6.0 on 2025-12-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_is_manual_to_shopping_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='is_pantry_item',
            field=models.BooleanField(default=False, help_text='Item is a pantry staple (included for verification)'),
        ),
    ]
