# Generated by Django 6.0 on 2025-12-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_is_pantry_item_to_shoppinglistitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plannedmeal',
            options={'ordering': ['week_plan', 'day_offset', 'is_supplementary']},
        ),
        migrations.AlterUniqueTogether(
            name='plannedmeal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='plannedmeal',
            name='is_supplementary',
            field=models.BooleanField(default=False, help_text="True for supplementary meals (e.g., kids' meals)"),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='is_pantry_staple',
            field=models.BooleanField(default=False, help_text='If true, flagged on shopping lists for verification'),
        ),
        migrations.AlterUniqueTogether(
            name='plannedmeal',
            unique_together={('week_plan', 'day_offset', 'is_supplementary')},
        ),
    ]
