# Generated by Django 6.0 on 2025-12-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_supplementary_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='is_starred',
            field=models.BooleanField(default=False, help_text='User marked as checked in pantry'),
        ),
    ]
