# Generated by Django 6.0 on 2025-12-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shoppinglistitem_is_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedmeal',
            name='for_people',
            field=models.CharField(blank=True, help_text="e.g., 'Harvey and Sophie' - who this meal is for", max_length=50),
        ),
    ]
