# Generated by Django 6.0 on 2025-12-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_plannedmeal_for_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='reference',
            field=models.URLField(blank=True, help_text='Link to the original recipe online'),
        ),
    ]
