# Generated by Django 6.0 on 2026-01-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_recipe_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ace_tag',
            field=models.BooleanField(default=False, help_text='Marked as a favourite recipe'),
        ),
    ]
