# Generated by Django 6.0 on 2026-01-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_recipe_ace_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='generated_at',
            field=models.DateTimeField(blank=True, help_text='When this list was last generated from a meal plan', null=True),
        ),
        migrations.AddField(
            model_name='weekplan',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='When the plan was last modified'),
        ),
    ]
