# Generated by Django 6.0 on 2026-01-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_shoppinglist_generated_at_weekplan_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekplan',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='If true, shuffling is disabled'),
        ),
    ]
