# Generated by Django 6.0 on 2026-01-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_weekplan_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedmeal',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text="If true, this meal won't be replaced during shuffle"),
        ),
    ]
